#!/bin/sh
# /etc/init.d/openq-820-blue-led-blink
#
### BEGIN INIT INFO
# Provides:          openq-820-blue-led-blink
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: sets blue led blink frequency
### END INIT INFO
case "$1" in
  start)
    echo "Starting script openq-820-blue-led-blink"
    echo 500 > /sys/class/leds/openq-820:blue:user1/delay_on
    echo 2000 > /sys/class/leds/openq-820:blue:user1/delay_off
    ;;
  stop)
    echo "Stopping script openq-820-blue-led-blink"
    echo 500 > /sys/class/leds/openq-820:blue:user1/delay_on
    echo 500 > /sys/class/leds/openq-820:blue:user1/delay_off
    ;;
  *)
    echo "Usage: /etc/init.d/openq-820-blue-led-blink {start|stop}"
    exit 1
    ;;
esac

exit 0
